---
# apache_php.yml : playbook for LAMP server

- hosts: lamp
  remote_user: vagrant
  become: yes
  
  pre_tasks:
    - shell: echo 'I ":" Beginning to configure Drush and Drupal...'
  
  roles: 
    - role: drupal 
 
  post_tasks:
    - shell: echo 'I ":" Done configuring Drush and Drupal!'
