---
# nodejs.yml : playbook for web servers

- hosts: node.js
  remote_user: vagrant
  become: yes
  
  pre_tasks:
    - shell: echo 'I ":" Beginning to configure web server...'
  
  roles: 
    - { role: nodejs, when: ansible_os_family == 'RedHat' }
  
  post_tasks:
    - shell: echo 'I ":" Done configuring nginx web server!'
