---
#- hosts: lamp

#  vars_files:
#    - vars.yml

#  pre_tasks:
#    - name: Update apt cache if needed
#      apt: update_cache=yes cache_valid_time=3600

#  handlers:
#    - name: restart apache
#      service: name=apache2 state=restarted
 
#  tasks:
- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600
 
- name: Get software for apt repository management
  apt: name={{ item }} state=present
  with_items:
     - python-apt
    
- name: Add ondrej repository for later versions of PHP
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: Get software for apt repository management
  apt: name={{ item }} state=present
  with_items:
    - git
    - curl
    - sendmail
    - apache2
    - php5
    - php5-common
    - php5-mysql
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-dev
    - php5-mcrypt
    - php-apc
    - php-pear
    - python-mysqldb
    - mysql-server

- name: Disable the firewall (for testing)
  service: name=ufw state=stopped

- name: "Start Apache, MySQL and PHP"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - apache2
    - mysql
    
- name: Enable Apache rewrite module (required for Drupal)
  apache2_module: name=rewrite state=present
  notify: restart apache

- name: Add Apache virtualhost for Drupal 8 development
  template:
    src: "templates/drupal.dev.conf.j2"
    dest: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Symlynk Drupal virtualhost to sites-enabled
  file:
    src: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
    dest: "/etc/apache2/sites-enabled/{{ domain }}.dev.conf"
    state: link
  notify: restart apache

- name: Remove default virtualhost file
  file:
   path: "/etc/apache2/sites-enabled/000-default.conf"
   state: absent
  notify: restart apache

- name: Enable upload progress via APC
  lineinfile:
    dest: "/etc/php5/apache2/conf.d/20-apcu.ini"
    regexp: "^apc.rfc1867"
    line: "apc.rfc1867 = 1"
    state: present
  notify: restart apache
