---
# filename: roles/nodejs/tasks/main.yml

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Ensure NTP is installed
    yum: name=ntp state=present

  - name: Ensure NTP is running
    service: name=ntpd state=started enabled=yes

  - name: Import remi GPG Key
    rpm_key: "key={{ item }} state=present"
    with_items:
      - "https://rpms.remirepo.net/RPM-GPG-KEY-remi"

  - name: Install Remi repo
    command: "rpm -Uvh --force {{ item.href }} creates={{ item.creates }}"
    with_items:
      - href: "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"
        creates: "/etc/yum.repos.d/remi.repo"

  - name: Install EPEL repo
    yum: name=epel-release state=present

  - name: Ensure firewalld is stopped (testing)
    service: name=firewalld state=stopped
  
  - name: Install Node.js and npm
    yum: name=npm state=present enablerepo=epel

  - name: Install Forever (to run our Node.js app)
    npm: name=forever global=yes state=latest

  - name: Ensure Node.js app folder exists
    file: "path={{ node_apps_location }} state=directory"

  - name: Copy example Node.js app to server
    copy: "src=files/app dest={{ node_apps_location }}"

  - name: Install package dependencies defined in package.json
    npm: path={{ node_apps_location }}/app

  - name: Check list of running Node.js apps
    command: forever list
    register: forever_list
    changed_when: false

  - name: Print Forever list stdout
    debug: 
      msg: "Nodejs forever list stdout: '{{ forever_list.stdout }}'"

  - name: Start example Node.js app
    command: "forever start {{ node_apps_location }}/app/app.js"
    when: "forever_list.stdout.find('{{ node_apps_location }}/app/app.js') == -1"
