---
# This is main.yml file for installing Solr

- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Install Tomcat 7
  apt: "name={{ item }} state=present"
  with_items: 
    - tomcat7
    - tomcat7-admin

- name: Ensure Tomcat 7 is started and enabled on boot
  service: name=tomcat7 state=started enabled=yes

- name: Download Solr
  get_url:
    url: "https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
#    url: "https://apache.osuosl.org/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
    dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
    checksum: "{{ solr_checksum }}"
#    sha256sum:  "{{ solr_sha256sum }}"

#- name: Expand Solr
#  command: >
#    tar -C /tmp -xvzf "{{ download_dir }}/solr-{{ solr_version }}.tgz"
#    creates={{ download_dir }}/solr-{{ solr_version }}/dist/solr-{{ solr_version }}.war


- name: Expand Solr.
  unarchive:
    src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
    dest: "{{ download_dir }}"
    copy: no
    creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

- name: Run Solr installation script.
  shell: >
    {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
    {{ download_dir }}/solr-{{ solr_version }}.tgz
    -i /opt
    -d /var/solr
    -u solr
    -s solr
    -p 8983
    creates={{ solr_dir }}/bin/solr

- name: Ensure solr is started and enabled on boot.
  service: name=solr state=started enabled=yes 

