---
# filename: Drupal playbook

- name: Check out Drupal Core to the Apache docroot
  git:
    repo: http://git.drupal.org/project/drupal.git
    version: "{{ drupal_core_version }}"
    dest: "{{ drupal_core_path }}"

- name: Install Drupal
  command: >
    drush si -y --site-name="{{ drupal_site_name }}"
    --account-name=admin
    --account-pass=admin
    --db-url=mysql://root@localhost/{{ domain }}
    chdir={{ drupal_core_path }}
    creates={{ drupal_core_path }}/sites/default/default.settings.php
  notify: restart apache

# SEE: https://drupal.org/node/2121849#comment-8413637
- name: Copy default-settings.php to settings.php
  command: >
    cp "{{ drupal_core_path }}/sites/default/default.settings.php" "{{ drupal_core_path }}/sites/default/settings.php"
    creates={{ drupal_core_path }}/sites/default/settings.php

- name: Set permissions properly on settings.php
  file:
    path: "{{ drupal_core_path }}/sites/default/settings.php"
    mode: 0766

- name: Set permissions on files and directory
  file:
    path: "{{ drupal_core_path }}/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes

