---
# apache_php.yml : playbook for LAMP server

- hosts: lamp
  remote_user: vagrant
  become: yes
  
  pre_tasks:
    - shell: echo 'I ":" Beginning to configure MYSQL server...'
  
  roles: 
    - { role: mysql, when: ansible_os_family == 'Debian' } 
 
  post_tasks:
    - shell: echo 'I ":" Done configuring MYSQL server!'
